Feature/general improvemments
gema/laravel-file-manager pull request #10
Opened 2022-03-30 15:00 UTC by marioSantos97

- Parent field changes (bugfixes, send parent path, hide/show parent field based on user parents)
- Add original media path to responses
- Other improvements

2022-04-02 17:54 UTC, promatik commented on package-lock.json
> -  "lockfileVersion": 2,
@marioSantos97 não migres este ficheiro para uma versão anterior do npm. Mantem na versão 2.

2022-04-02 17:57 UTC, promatik commented on src/resources/js/file-manager.js
> +    const container = document.querySelector(`#select2-container-${i}`);
O ESLint não está a correr aqui ...

2022-04-02 17:59 UTC, promatik commented on src/resources/views/filemanager.blade.php
> +            <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
Todas estas dependencias deviam vir do bundle.js, e deviam ser instaladas pelo npm.

2022-04-02 17:59 UTC, promatik requested changes
@marioSantos97 revê aqui os comentários que te deixei.

2022-04-04 12:34 UTC, marioSantos97 commented on src/resources/js/file-manager.js
> +    const container = document.querySelector(`#select2-container-${i}`);
Qual é o erro que tá a dar? A mim não aparece nada

2022-04-09 18:04 UTC, promatik approved these changes

2022-04-09 18:05 UTC, merged